package view;

import controller.EBO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.EVO;

public class Consultas extends javax.swing.JDialog {

    private DefaultTableModel modelo;

    public Consultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        //CONSTRUIR LA TABLA
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Fecha Nacimiento");
        modelo.addColumn("Correo Personal");
        modelo.addColumn("Número Celular");
        modelo.addColumn("Número Fijo");
        modelo.addColumn("Programa Académico");
        modelo.addColumn("Correo Institucional");
        jTableConsultas.setModel(modelo);
        List<EVO> estudiantes = new EBO().mostrarDirectorio();
        for (EVO serhumano : estudiantes) {
            String fila[] = {serhumano.getNombres(), serhumano.getApellidos(), serhumano.getFnacimiento(),
                serhumano.getCpersonal(), serhumano.getNcelular() + "", serhumano.getNfijo() + "",
                serhumano.getPrograma(), serhumano.getCinstitucional()};
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxConsultas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        jTextConsultas = new javax.swing.JTextField();
        jButtonConsultas = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();
        jButtonCantidad = new javax.swing.JButton();
        jLabelConteo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxConsultas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jComboBoxConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apellidos", "Programa", "Fecha nacimiento", "Celular", "Correo institucional" }));
        jComboBoxConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConsultasActionPerformed(evt);
            }
        });

        jTableConsultas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Fecha Nacimiento", "Correo Personal", "Número Celular", "Número Fijo", "Programa Académico", "Correo Institucional"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableConsultas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableConsultas.setColumnSelectionAllowed(true);
        jTableConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableConsultas);

        jTextConsultas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        jButtonConsultas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonConsultas.setText("CONSULTAR");
        jButtonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultasActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelTitulo.setText("CONSULTAS");

        jLabelCantidad.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelCantidad.setText("Número de estudiantes por programa");

        jTextCantidad.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        jButtonCantidad.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonCantidad.setText("CONTAR");
        jButtonCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCantidadActionPerformed(evt);
            }
        });

        jLabelConteo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabelConteo.setText("Total de estudiantes por consulta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(jLabelTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConsultas)
                        .addContainerGap(486, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCantidad)
                                .addGap(18, 18, 18)
                                .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCantidad))
                            .addComponent(jLabelConteo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelTitulo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultas))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelConteo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCantidad))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConsultasActionPerformed

    private void jButtonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultasActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        String Consultas = (String) jComboBoxConsultas.getSelectedItem();
        List<EVO> estudiantes = null;
        if (Consultas.equals("Apellidos")) {
            estudiantes = new EBO().buscarApellidos(jTextConsultas.getText());
        } else if (Consultas.equals("Programa")) {
            estudiantes = new EBO().buscarPrograma(jTextConsultas.getText());
        } else if (Consultas.equals("Fecha nacimiento")) {
            estudiantes = new EBO().buscarFnacimiento(jTextConsultas.getText());
        } else if (Consultas.equals("Celular")) {
            estudiantes = new EBO().buscarCelular(Long.parseLong(jTextConsultas.getText()));
        } else if (Consultas.equals("Correo institucional")){
            estudiantes = new ArrayList();
            estudiantes.add(new EBO().buscarCorreo(jTextConsultas.getText()));
        }
        for (EVO serhumano : estudiantes){
            String fila [] = {serhumano.getNombres(), serhumano.getApellidos(), serhumano.getFnacimiento(),
                serhumano.getCpersonal(), serhumano.getNcelular() + "", serhumano.getNfijo() + "",
                serhumano.getPrograma(), serhumano.getCinstitucional()};
            modelo.addRow(fila);
        }
        jLabelConteo.setText(estudiantes.size()+" ");
    }//GEN-LAST:event_jButtonConsultasActionPerformed

    private void jButtonCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCantidadActionPerformed
        // TODO add your handling code here:
        int resultado;
        resultado = new EBO().buscarCantidad(jTextCantidad.getText());
        JOptionPane.showMessageDialog(this, "Número de estudiantes: " + resultado);
    }//GEN-LAST:event_jButtonCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Consultas dialog = new Consultas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCantidad;
    private javax.swing.JButton jButtonConsultas;
    private javax.swing.JComboBox<String> jComboBoxConsultas;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelConteo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultas;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextConsultas;
    // End of variables declaration//GEN-END:variables
}
